networks:
  default:
    driver: bridge
    name: roboshop
    external: true # I created networks already using docker network create roboshop

volumes:
  mongodb: # docker volume creates MongoDB
  redis: # docker volume creates Redis
  mysql: # docker volume creates MySQL
  rabbitmq:  # docker volume creates RabbitMQ

services:
  mongodb:
    image: nagaraj411/mongodb:v1
    container_name: mongodb
    volumes:
    - mongodb:/data/db # The mongoDB data will be stored in a Docker volume in /data/db
  catalogue:
    image: nagaraj411/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  redis:
    image: redis:7.0  # Use the official Redis image
    container_name: redis
    volumes:
    - redis:/data # The Redis data will be stored in a Docker volume in /data
  user:
    image: nagaraj411/user:v1
    container_name: user
    depends_on:
    - mongodb
    - redis
  cart:
    image: nagaraj411/cart:v1
    container_name: cart
    depends_on:
    - catalogue
    - redis
  mysql:
    image: nagaraj411/mysql:v1
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql # The MySQL data will be stored in a Docker volume in /var/lib/mysql
  shipping:
    image: nagaraj411/shipping:v1
    container_name: shipping
    depends_on:
    - mysql
    - cart
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
    volumes:
    - rabbitmq:/var/lib/rabbitmq # The RabbitMQ data will be stored in a Docker volume in /var/lib/rabbitmq
  payment:
    image: nagaraj411/payment:v1
    container_name: payment
    environment:
      CART_HOST: cart
      CART_PORT: 8080
      USER_HOST: user
      USER_PORT: 8080
      AMQP_HOST: rabbitmq
      AMQP_USER: roboshop
      AMQP_PASS: roboshop123
    depends_on:
    - rabbitmq
    - cart
    - user
  frontend:
    image: nagaraj411/frontend:v1
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - shipping
    - payment
    restart: always