networks:
  default:
    driver: bridge
    name: roboshop
    #external: true # I created networks already using docker network create roboshop

services:
  mongodb:
    image: nagaraj411/mongodb:v1
    container_name: mongodb
  catalogue:
    image: nagaraj411/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  redis:
    image: redis:7.0  # Use the official Redis image
    container_name: redis
  user:
    image: nagaraj411/user:v1
    container_name: user
    depends_on:
    - mongodb
    - redis
  cart:
    image: nagaraj411/cart:v1
    container_name: cart
    depends_on:
    - catalogue
    - redis
  mysql:
    image: nagaraj411/mysql:v1
    container_name: mysql
  shipping:
    image: nagaraj411/shipping:v1
    container_name: shipping
    depends_on:
    - mysql
    - cart
    